//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_IT_COMBOS
    {
        public int ID { get; set; }
        public string OWNER { get; set; }
        public string LAPTOP_SN { get; set; }
        public string DOCK_SN { get; set; }
        public string WEBCAM_SN { get; set; }
        public string HEADSET_SN { get; set; }
    }
}
