//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_IT_ASSETS
    {
        public int ID { get; set; }
        public string ASSET_TYPE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string CATEGORY { get; set; }
        public string MAKE { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<int> ASSET_NUMBER { get; set; }
        public string TAGGABLE { get; set; }
        public string ALLOCATED_TO { get; set; }
        public string EMAIL_ID { get; set; }
        public int PO_NO { get; set; }
        public string EOL_or_EOS { get; set; }
        public string EOL_EOS_DATE { get; set; }
    }
}
